name: Lyrebird Java Client CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit Test
      run: mvn clean verify

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml

  deploy:
    if: github.event_name == 'push' && github.event.type == 'tags'
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Package Registry
      env:
        GITHUB_TOKEN: bd11b20f05aad3a1a2d33938498d78b9ee86fcda
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/reeyur -Dtoken=bd11b20f05aad3a1a2d33938498d78b9ee86fcda
