name: Lyrebird Java Client Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Package Registry
      env:
        GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      run: |
        echo "${GPG_SECRET_KEYS}" | gpg --batch --import
        echo auto-key-retrieve > ~/.gnupg/gpg.conf
        mvn --settings settings.xml deploy -B -U -P release